name = "HistogramThresholding"
uuid = "2c695a8d-9458-5d45-9878-1b8a99cf7853"
authors = ["Dr. Zygmunt L. Szpak <zygmunt.szpak@gmail.com>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "^1"

[extras]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ImageContrastAdjustment = "f332f351-ec65-5f6a-b3d1-319c6670881a"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["ImageContrastAdjustment", "ImageCore", "ColorTypes", "TestImages", "Test", "ImageMagick"]
